//
//  StyleKit.swift
//  EventBuilder
//
//  Created by Buu Bui on 4/20/16.
//  Copyright (c) 2016 Buu Bui. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {

    //// Drawing Methods

    public class func drawCalendar(frame frame: CGRect = CGRectMake(0, 0, 400, 400), calendarColor: UIColor = UIColor(red: 0.910, green: 0.925, blue: 0.933, alpha: 1.000), wandColor: UIColor = UIColor(red: 0.910, green: 0.925, blue: 0.933, alpha: 1.000)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Subframes
        let frame2 = CGRectMake(frame.minX + floor(frame.width * 0.04000 + 0.5), frame.minY + floor(frame.height * 0.31750 + 0.5), floor(frame.width * 0.95500 + 0.5) - floor(frame.width * 0.04000 + 0.5), floor(frame.height * 0.96000 + 0.5) - floor(frame.height * 0.31750 + 0.5))


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.22000 * frame.width, frame.minY + 0.00000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.19125 * frame.width, frame.minY + 0.01125 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.20955 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.19879 * frame.width, frame.minY + 0.00371 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.18000 * frame.width, frame.minY + 0.04000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.18371 * frame.width, frame.minY + 0.01879 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.18000 * frame.width, frame.minY + 0.02955 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.18000 * frame.width, frame.minY + 0.08000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.04000 * frame.width, frame.minY + 0.08000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.01125 * frame.width, frame.minY + 0.09125 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.02955 * frame.width, frame.minY + 0.08000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.01879 * frame.width, frame.minY + 0.08371 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.12000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.00371 * frame.width, frame.minY + 0.09879 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.10955 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.96000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.01125 * frame.width, frame.minY + 0.98875 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.97045 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.00371 * frame.width, frame.minY + 0.98121 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.04000 * frame.width, frame.minY + 1.00000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.01879 * frame.width, frame.minY + 0.99629 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.02955 * frame.width, frame.minY + 1.00000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.96000 * frame.width, frame.minY + 1.00000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.98875 * frame.width, frame.minY + 0.98875 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.97045 * frame.width, frame.minY + 1.00000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.98121 * frame.width, frame.minY + 0.99629 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.96000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.99629 * frame.width, frame.minY + 0.98121 * frame.height), controlPoint2: CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.97045 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.12000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.98875 * frame.width, frame.minY + 0.09125 * frame.height), controlPoint1: CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.10955 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.99629 * frame.width, frame.minY + 0.09879 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.96000 * frame.width, frame.minY + 0.08000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.98121 * frame.width, frame.minY + 0.08371 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.97045 * frame.width, frame.minY + 0.08000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.82000 * frame.width, frame.minY + 0.08000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.82000 * frame.width, frame.minY + 0.04000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.80875 * frame.width, frame.minY + 0.01125 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.82000 * frame.width, frame.minY + 0.02955 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.81629 * frame.width, frame.minY + 0.01879 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.78000 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.80121 * frame.width, frame.minY + 0.00371 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.79045 * frame.width, frame.minY + 0.00000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.74000 * frame.width, frame.minY + 0.00000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.71125 * frame.width, frame.minY + 0.01125 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.72955 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.71879 * frame.width, frame.minY + 0.00371 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.70000 * frame.width, frame.minY + 0.04000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.70371 * frame.width, frame.minY + 0.01879 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.70000 * frame.width, frame.minY + 0.02955 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.70000 * frame.width, frame.minY + 0.08000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.30000 * frame.width, frame.minY + 0.08000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.30000 * frame.width, frame.minY + 0.04000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.28875 * frame.width, frame.minY + 0.01125 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.30000 * frame.width, frame.minY + 0.02955 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.29629 * frame.width, frame.minY + 0.01879 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.26000 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.28121 * frame.width, frame.minY + 0.00371 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.27045 * frame.width, frame.minY + 0.00000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.22000 * frame.width, frame.minY + 0.00000 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.22000 * frame.width, frame.minY + 0.04000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.26000 * frame.width, frame.minY + 0.04000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.26000 * frame.width, frame.minY + 0.16000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.22000 * frame.width, frame.minY + 0.16000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.22000 * frame.width, frame.minY + 0.04000 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.74000 * frame.width, frame.minY + 0.04000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.78000 * frame.width, frame.minY + 0.04000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.78000 * frame.width, frame.minY + 0.16000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.74000 * frame.width, frame.minY + 0.16000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.74000 * frame.width, frame.minY + 0.04000 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.04000 * frame.width, frame.minY + 0.12000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.18000 * frame.width, frame.minY + 0.12000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.18000 * frame.width, frame.minY + 0.16000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.19125 * frame.width, frame.minY + 0.18875 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.18000 * frame.width, frame.minY + 0.17045 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.18371 * frame.width, frame.minY + 0.18121 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.22000 * frame.width, frame.minY + 0.20000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.19879 * frame.width, frame.minY + 0.19629 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.20955 * frame.width, frame.minY + 0.20000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.26000 * frame.width, frame.minY + 0.20000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.28875 * frame.width, frame.minY + 0.18875 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.27045 * frame.width, frame.minY + 0.20000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.28121 * frame.width, frame.minY + 0.19629 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.30000 * frame.width, frame.minY + 0.16000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.29629 * frame.width, frame.minY + 0.18121 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.30000 * frame.width, frame.minY + 0.17045 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.30000 * frame.width, frame.minY + 0.12000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.70000 * frame.width, frame.minY + 0.12000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.70000 * frame.width, frame.minY + 0.16000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.71125 * frame.width, frame.minY + 0.18875 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.70000 * frame.width, frame.minY + 0.17045 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.70371 * frame.width, frame.minY + 0.18121 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.74000 * frame.width, frame.minY + 0.20000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.71879 * frame.width, frame.minY + 0.19629 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.72955 * frame.width, frame.minY + 0.20000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.78000 * frame.width, frame.minY + 0.20000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.80875 * frame.width, frame.minY + 0.18875 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.79045 * frame.width, frame.minY + 0.20000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.80121 * frame.width, frame.minY + 0.19629 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.82000 * frame.width, frame.minY + 0.16000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.81629 * frame.width, frame.minY + 0.18121 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.82000 * frame.width, frame.minY + 0.17045 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.82000 * frame.width, frame.minY + 0.12000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.96000 * frame.width, frame.minY + 0.12000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.96000 * frame.width, frame.minY + 0.28000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.04000 * frame.width, frame.minY + 0.28000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.04000 * frame.width, frame.minY + 0.12000 * frame.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(frame2.minX + 0.00000 * frame2.width, frame2.minY + 0.00389 * frame2.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.96000 * frame.width, frame.minY + 0.32000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.96000 * frame.width, frame.minY + 0.96000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame2.minX + 0.00000 * frame2.width, frame2.minY + 1.00000 * frame2.height))
        bezierPath.addLineToPoint(CGPointMake(frame2.minX + 0.00000 * frame2.width, frame2.minY + 0.00389 * frame2.height))
        bezierPath.closePath()
        bezierPath.lineJoinStyle = .Bevel;

        calendarColor.setFill()
        bezierPath.fill()


        //// Symbol Drawing
        let symbolRect = CGRectMake(frame2.minX + floor(frame2.width * 0.23770 + 0.5), frame2.minY + floor(frame2.height * 0.12062 + 0.5), floor(frame2.width * 0.76776 + 0.5) - floor(frame2.width * 0.23770 + 0.5), floor(frame2.height * 0.87549 + 0.5) - floor(frame2.height * 0.12062 + 0.5))
        CGContextSaveGState(context)
        UIRectClip(symbolRect)
        CGContextTranslateCTM(context, symbolRect.origin.x, symbolRect.origin.y)

        StyleKit.drawWand(frame: CGRectMake(0, 0, symbolRect.size.width, symbolRect.size.height), wandColor: wandColor)
        CGContextRestoreGState(context)
    }

    public class func drawWand(frame frame: CGRect = CGRectMake(0, 0, 500, 500), wandColor: UIColor = UIColor(red: 0.910, green: 0.925, blue: 0.933, alpha: 1.000)) {

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.18402 * frame.width, frame.minY + 0.13802 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.28400 * frame.width, frame.minY + 0.19400 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.38398 * frame.width, frame.minY + 0.13802 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.32800 * frame.width, frame.minY + 0.23800 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.38398 * frame.width, frame.minY + 0.33798 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.28400 * frame.width, frame.minY + 0.28200 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.18402 * frame.width, frame.minY + 0.33798 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.24000 * frame.width, frame.minY + 0.23800 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.18402 * frame.width, frame.minY + 0.13802 * frame.height))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.66402 * frame.width, frame.minY + 0.61802 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.76400 * frame.width, frame.minY + 0.67400 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.86398 * frame.width, frame.minY + 0.61802 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.80800 * frame.width, frame.minY + 0.71800 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.86398 * frame.width, frame.minY + 0.81798 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.76400 * frame.width, frame.minY + 0.76200 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.66402 * frame.width, frame.minY + 0.81798 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.72000 * frame.width, frame.minY + 0.71800 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.66402 * frame.width, frame.minY + 0.61802 * frame.height))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.66402 * frame.width, frame.minY + 0.13802 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.76400 * frame.width, frame.minY + 0.19400 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.86398 * frame.width, frame.minY + 0.13802 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.80800 * frame.width, frame.minY + 0.23800 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.86398 * frame.width, frame.minY + 0.33798 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.76400 * frame.width, frame.minY + 0.28200 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.66402 * frame.width, frame.minY + 0.33798 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.72000 * frame.width, frame.minY + 0.23800 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.66402 * frame.width, frame.minY + 0.13802 * frame.height))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.53200 * frame.width, frame.minY + 0.42600 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.52130 * frame.width, frame.minY + 0.42738 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.52830 * frame.width, frame.minY + 0.42600 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52471 * frame.width, frame.minY + 0.42648 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.49000 * frame.width, frame.minY + 0.46800 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.50329 * frame.width, frame.minY + 0.43211 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.49000 * frame.width, frame.minY + 0.44850 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.53200 * frame.width, frame.minY + 0.51000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.49000 * frame.width, frame.minY + 0.49120 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.50880 * frame.width, frame.minY + 0.51000 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.57400 * frame.width, frame.minY + 0.46800 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.55520 * frame.width, frame.minY + 0.51000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.57400 * frame.width, frame.minY + 0.49120 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.53200 * frame.width, frame.minY + 0.42600 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.57400 * frame.width, frame.minY + 0.44480 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.55520 * frame.width, frame.minY + 0.42600 * frame.height))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(frame.minX + 0.55566 * frame.width, frame.minY + 0.34578 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.56940 * frame.width, frame.minY + 0.35740 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.56007 * frame.width, frame.minY + 0.34807 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.56318 * frame.width, frame.minY + 0.35118 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.64338 * frame.width, frame.minY + 0.43138 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.65460 * frame.width, frame.minY + 0.44445 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.64961 * frame.width, frame.minY + 0.43761 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.65272 * frame.width, frame.minY + 0.44072 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.65501 * frame.width, frame.minY + 0.44513 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.65501 * frame.width, frame.minY + 0.46087 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.65734 * frame.width, frame.minY + 0.45012 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.65734 * frame.width, frame.minY + 0.45588 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.64338 * frame.width, frame.minY + 0.47462 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.65272 * frame.width, frame.minY + 0.46528 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.64961 * frame.width, frame.minY + 0.46839 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.16827 * frame.width, frame.minY + 0.94973 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.15520 * frame.width, frame.minY + 0.96094 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.16205 * frame.width, frame.minY + 0.95595 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.15894 * frame.width, frame.minY + 0.95906 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.15453 * frame.width, frame.minY + 0.96136 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.13878 * frame.width, frame.minY + 0.96136 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.14954 * frame.width, frame.minY + 0.96368 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.14377 * frame.width, frame.minY + 0.96368 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.12504 * frame.width, frame.minY + 0.94973 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.13437 * frame.width, frame.minY + 0.95906 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.13126 * frame.width, frame.minY + 0.95595 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.05106 * frame.width, frame.minY + 0.87575 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.03984 * frame.width, frame.minY + 0.86268 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.04483 * frame.width, frame.minY + 0.86952 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.04172 * frame.width, frame.minY + 0.86641 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.03943 * frame.width, frame.minY + 0.86200 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.03943 * frame.width, frame.minY + 0.84626 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.03710 * frame.width, frame.minY + 0.85701 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.03710 * frame.width, frame.minY + 0.85125 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.05106 * frame.width, frame.minY + 0.83251 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.04172 * frame.width, frame.minY + 0.84185 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.04483 * frame.width, frame.minY + 0.83874 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.52617 * frame.width, frame.minY + 0.35740 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.52680 * frame.width, frame.minY + 0.35677 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.52638 * frame.width, frame.minY + 0.35719 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.52659 * frame.width, frame.minY + 0.35698 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.53924 * frame.width, frame.minY + 0.34619 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.53261 * frame.width, frame.minY + 0.35097 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.53563 * frame.width, frame.minY + 0.34800 * frame.height))
        bezier2Path.addLineToPoint(CGPointMake(frame.minX + 0.53991 * frame.width, frame.minY + 0.34578 * frame.height))
        bezier2Path.addCurveToPoint(CGPointMake(frame.minX + 0.55566 * frame.width, frame.minY + 0.34578 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.54490 * frame.width, frame.minY + 0.34345 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.55067 * frame.width, frame.minY + 0.34345 * frame.height))
        bezier2Path.closePath()
        wandColor.setFill()
        bezier2Path.fill()
    }

    //// Generated Images

    public class func imageOfCalendar(frame frame: CGRect = CGRectMake(0, 0, 400, 400), calendarColor: UIColor = UIColor(red: 0.910, green: 0.925, blue: 0.933, alpha: 1.000), wandColor: UIColor = UIColor(red: 0.910, green: 0.925, blue: 0.933, alpha: 1.000)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            StyleKit.drawCalendar(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), calendarColor: calendarColor, wandColor: wandColor)

        let imageOfCalendar = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfCalendar
    }

}
